---
- hosts: 172.31.22.72
  become: yes
  tasks:
  - include_tasks: myfiles.yml

  - name: install webserver
    apt: 
     name: apache2
     state: present

  - name: copy index.html file into node side
    copy:
      src: myindex.html
      dest: /var/www/html/index.html

  - name: copy index.j2 file into node side
    template:
         src: myindex.j2
         dest: /var/www/html/index.html   

  - name: download file and force basic auth
    get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz
      dest: /home/ubuntu
      force_basic_auth: yes
