---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: install webserver on node side
    apt:
     name: apache2
     state: present
    when: ansible_os_family=="Debian"   

  - name: start the web server
    service:
        name: apache2
        state: started
    when: ansible_os_family=="Debian"    


  - name: install webserver redhat node side
    yum:
     name: httpd
     state: present
    when: ansible_os_family=="RedHat" 

  - name: restart httpd server
    service:
        name: httpd
        state: started  
    when: ansible_os_family=="RedHat"    
