---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks:
  - name: install webserver on node side
    apt:
     name: "{{mywebpackonubuntu}}"
     state: present
    when: ansible_os_family=="Debian"   

  - name: start the web server
    service:
        name: "{{mywebpackonubuntu}}"
        state: started
    when: ansible_os_family=="Debian"    


  - name: install webserver redhat node side
    yum:
     name: "{{mywebpackonredhat}}"
     state: present
    when: ansible_os_family=="RedHat" 

  - name: restart httpd server
    service:
        name: "{{mywebpackonredhat}}"
        state: started  
    when: ansible_os_family=="RedHat"    
