---
- name: download file and force basic auth
  get_url:
    url: https://downloads.apache.org/tomcat/tomcat-10/v10.0.22/bin/apache-tomcat-10.0.22.zip
    dest: /home/ubuntu/apache-tomcat-10.0.22.zip
    force_basic_auth: yes


- name: create a folder
  file:
    path: /opt/tomcat
    state: directory    


- name: extract tar file
  command:
    cmd: sudo tar xzvf /home/ubuntu/apache-tomcat-10.0.22.zip -C /opt/tomcat --strip-components=1
    creates: /opt/tomcat/LICENSE